version: "3.8"

networks:
  monitoring: {}

volumes:
 prometheus_data: {}

services:
  graf:
    image: grafana/grafana
    container_name: graf
    restart: always
    ports:
      - 3000
    networks:
      - mon
  
  prom:
    image: prom/prometheus:latest
    container_name: prom
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090
    networks:
      - mon

